// Code generated by Kitex v0.4.4. DO NOT EDIT.

package favoriteservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	FavoriteServer "github.com/xiaohei366/TinyTiktok/cmd/favorite/kitex_gen/FavoriteServer"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FavoriteAction(ctx context.Context, Req *FavoriteServer.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (r *FavoriteServer.DouyinFavoriteActionResponse, err error)
	GetFavoriteList(ctx context.Context, Req *FavoriteServer.DouyinFavoriteListRequest, callOptions ...callopt.Option) (r *FavoriteServer.DouyinFavoriteListResponse, err error)
	GetFavoriteUser(ctx context.Context, Req *FavoriteServer.DouyinUserFavoriteRequest, callOptions ...callopt.Option) (r *FavoriteServer.DouyinUserFavoriteResponse, err error)
	GetFavoriteVideo(ctx context.Context, Req *FavoriteServer.DouyinVideoFavoriteRequest, callOptions ...callopt.Option) (r *FavoriteServer.DouyinVideoFavoriteResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFavoriteServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFavoriteServiceClient struct {
	*kClient
}

func (p *kFavoriteServiceClient) FavoriteAction(ctx context.Context, Req *FavoriteServer.DouyinFavoriteActionRequest, callOptions ...callopt.Option) (r *FavoriteServer.DouyinFavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteAction(ctx, Req)
}

func (p *kFavoriteServiceClient) GetFavoriteList(ctx context.Context, Req *FavoriteServer.DouyinFavoriteListRequest, callOptions ...callopt.Option) (r *FavoriteServer.DouyinFavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFavoriteList(ctx, Req)
}

func (p *kFavoriteServiceClient) GetFavoriteUser(ctx context.Context, Req *FavoriteServer.DouyinUserFavoriteRequest, callOptions ...callopt.Option) (r *FavoriteServer.DouyinUserFavoriteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFavoriteUser(ctx, Req)
}

func (p *kFavoriteServiceClient) GetFavoriteVideo(ctx context.Context, Req *FavoriteServer.DouyinVideoFavoriteRequest, callOptions ...callopt.Option) (r *FavoriteServer.DouyinVideoFavoriteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFavoriteVideo(ctx, Req)
}
