// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/hertz-contrib/pprof"
	"github.com/xiaohei366/TinyTiktok/cmd/api/initialize"
	"github.com/xiaohei366/TinyTiktok/pkg/shared"
)

func main() {
	initialize.Init()
	//链路追踪
	tracer, cfg := hertztracing.NewServerTracer()
	h := server.New(
		server.WithHostPorts(shared.ApiServiceAddr),
		server.WithHandleMethodNotAllowed(true), // coordinate with NoMethod
		server.WithMaxRequestBodySize(10000000000),
		tracer,
	)
	// 使用 pprof 和 tracer 两个中间件
	pprof.Register(h)
	h.Use(hertztracing.ServerMiddleware(cfg))
	//设定好路由并启动
	register(h)
	h.Spin()
}
