// Code generated by Kitex v0.4.4. DO NOT EDIT.
package videosrv

import (
	server "github.com/cloudwego/kitex/server"
	"github.com/xiaohei366/TinyTiktok/cmd/api/biz/kitex_gen/VideoServer"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler VideoServer.VideoSrv, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
