// Code generated by Kitex v0.4.4. DO NOT EDIT.

package feedsrv

import (
	"context"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	"github.com/xiaohei366/TinyTiktok/cmd/api/biz/kitex_gen/FeedServer"
	proto "google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return feedSrvServiceInfo
}

var feedSrvServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FeedSrv"
	handlerType := (*FeedServer.FeedSrv)(nil)
	methods := map[string]kitex.MethodInfo{
		"douyin_feed": kitex.NewMethodInfo(douyinFeedHandler, newDouyinFeedArgs, newDouyinFeedResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "FeedServer",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func douyinFeedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(FeedServer.DouyinFeedRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(FeedServer.FeedSrv).DouyinFeed(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *DouyinFeedArgs:
		success, err := handler.(FeedServer.FeedSrv).DouyinFeed(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DouyinFeedResult)
		realResult.Success = success
	}
	return nil
}
func newDouyinFeedArgs() interface{} {
	return &DouyinFeedArgs{}
}

func newDouyinFeedResult() interface{} {
	return &DouyinFeedResult{}
}

type DouyinFeedArgs struct {
	Req *FeedServer.DouyinFeedRequest
}

func (p *DouyinFeedArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(FeedServer.DouyinFeedRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DouyinFeedArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DouyinFeedArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DouyinFeedArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in DouyinFeedArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *DouyinFeedArgs) Unmarshal(in []byte) error {
	msg := new(FeedServer.DouyinFeedRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DouyinFeedArgs_Req_DEFAULT *FeedServer.DouyinFeedRequest

func (p *DouyinFeedArgs) GetReq() *FeedServer.DouyinFeedRequest {
	if !p.IsSetReq() {
		return DouyinFeedArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DouyinFeedArgs) IsSetReq() bool {
	return p.Req != nil
}

type DouyinFeedResult struct {
	Success *FeedServer.DouyinFeedResponse
}

var DouyinFeedResult_Success_DEFAULT *FeedServer.DouyinFeedResponse

func (p *DouyinFeedResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(FeedServer.DouyinFeedResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DouyinFeedResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DouyinFeedResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DouyinFeedResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in DouyinFeedResult")
	}
	return proto.Marshal(p.Success)
}

func (p *DouyinFeedResult) Unmarshal(in []byte) error {
	msg := new(FeedServer.DouyinFeedResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DouyinFeedResult) GetSuccess() *FeedServer.DouyinFeedResponse {
	if !p.IsSetSuccess() {
		return DouyinFeedResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DouyinFeedResult) SetSuccess(x interface{}) {
	p.Success = x.(*FeedServer.DouyinFeedResponse)
}

func (p *DouyinFeedResult) IsSetSuccess() bool {
	return p.Success != nil
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) DouyinFeed(ctx context.Context, Req *FeedServer.DouyinFeedRequest) (r *FeedServer.DouyinFeedResponse, err error) {
	var _args DouyinFeedArgs
	_args.Req = Req
	var _result DouyinFeedResult
	if err = p.c.Call(ctx, "douyin_feed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
