// Code generated by Kitex v0.4.4. DO NOT EDIT.

<<<<<<<< HEAD:kitex_gen/VideoServer/videosrv/invoker.go
package videosrv

import (
	server "github.com/cloudwego/kitex/server"
	VideoServer "github.com/xiaohei366/TinyTiktok/kitex_gen/VideoServer"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler VideoServer.VideoSrv, opts ...server.Option) server.Invoker {
========
package relationservice

import (
	server "github.com/cloudwego/kitex/server"
	RelationServer "github.com/xiaohei366/TinyTiktok/kitex_gen/RelationServer"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler RelationServer.RelationService, opts ...server.Option) server.Invoker {
>>>>>>>> origin/user&follow:kitex_gen/RelationServer/relationservice/invoker.go
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
